name: "Pepe Hernández"
description: "Blog personal de Pepe Hernández"

url: "http://pphdez.github.io"

paginate: 10

markdown: rdiscount
permalink: pretty
comments: true

jekyll_ga:
  service_account_email: 1036883075932-2guov2upgnqct3ktrukkopbeshocp744@developer.gserviceaccount.com   
  key_file: privatekey.p12
  key_secret: notasecret
  profileID: ga:77649816         
  start: last month         
  end: now
  metric: ga:pageviews  
  segment:              
  filters:              
  sort: false           
jekyll_sort:
  - src: posts
    by: _ga
    direction: down
    dest: posts_popular

exclude: [privatekey.p12]
